server: 
  port: 8080

spring: 
  mvc: 
    view: 
      prefix: /views/
      suffix:  html
  data: 
    redis: 

dataSource: 
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
  driver-class: com.mysql.jdbc.Driver
  max-active: 10
  initial-size: 3
  min-idle: 2
  max-wait: 5000
  test-on-borrow: true

mapper: 
  location: classpath:/mapper/*.xml
  typePackage: org.xy.domain